version: "3.8"

services:
  db:
    image: postgres:14
    container_name: factori_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: arsh
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: factori
    volumes:
      - ./sql/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    restart: unless-stopped
